url: "https://cristiangaleano2003.github.io"
baseurl: ""

# Site settings
title: Cristian Data & Code
email: cristianygaleanod@gmail.com
description: "Soy Data Analyst experto en convertir información en valor estratégico, optimizando procesos y creando estructuras seguras y escalables. Ayudo a las empresas a pasar de datos crudos a insights accionables que impulsan resultados."


# Team names, titles and social links
people:
- name: Cristian Galeano
  pic: 1
  position: Data Analyst
  social:
    - title: linkedin
      url: https://linkedin.com/in/cristian-galeano-diaz-analista-datos 
    - title: github
      url: https://github.com/CristianGaleano2003
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: Bogotá D.C., Colombia
  
# Build settings
markdown: kramdown
permalink: pretty